#%RAML 1.0
title: API that performs Mule-CoAP-Connector tests. 

baseUri: /

resourceTypes:
  etsi-plugtest:
    description: Perform ETSI plugtest 
    get:
      queryParameters: 
        host:
          description: Hostname or ip of CoAP server that will be used. Default the internal test server is used (127.0.0.1).
          type: string
          required: false
          example: californium.eclipse.org
        port:
          description: Port number of the CoAP server. Defaults to standard CoAP port (5683).
          type: integer
          required: false
          example: 5683
      responses:
        200:
          description:  Test succeeded.
          body: 
            text/plain:
              description: "test result"
        404:
          description: Resource not found
          body: 
            text/plain:
              description: "error message"
        405:
          description: Method not allowed
          body: 
            text/plain:
              description: "error message"
        415:
          description: Unsupported media type
          body: 
            text/plain:
              description: "error message"
        406:
          description: Not acceptable
          body: 
            text/plain:
              description: "error message"
        400:
          description: Bad request
          body: 
            text/plain:
              description: "error message"
        500:
          description: Internal server error.
          body: 
            text/plain:         
              description: "error message"
        502:
          description: CoAP response indicated failure or timeout.
          body: 
            text/plain:
              description: "error message"


/etsi-plugtest:
  description: "ETSI Plugtests: 
    See ETSI CTI Plugtests Guide V0.0.13 (2012-11)
    https://portal.etsi.org/cti/downloads/TestSpecifications/CoAP_2_Plugtests_TestDescriptions_v013.pdf"
   
  /TD_COAP_CORE_01:
    description: Perform GET transaction (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a GET request with:
        Type = 0(CON)
        Code = 1(GET)"
      responses:
        200:
          description: "Server sends response containing:
            Code = 69(2.05 Content)
            The same Message ID as that of the request sent by the client
            Content format option"
           
  /TD_COAP_CORE_02:
    description: Perform DELETE transaction (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a DELETE request with:
        Type = 0(CON)
        Code = 4(DELETE)"
      responses:
        200:
          description: "Server sends response containing:
            Code = 66(2.02 Deleted)
            The same Message ID as that of the request sent by the
            client"

  /TD_COAP_CORE_03:
    description: Perform PUT transaction (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a PUT request with:
        Type = 0(CON)
        Code = 3(PUT)
        An arbitrary payload
        Content format option"
      responses:
        200:
          description: "Server sends response containing:
            Code = 68 (2.04 Changed) or 65 (2.01 Created)
            The same Message ID as that of the request sent by the
            client"

  /TD_COAP_CORE_04:
    description: Perform POST transaction (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a POST request with:
        Type = 0(CON)
        Code = 2(POST)
        An arbitrary payload
        Content format option"
      responses:
        200:
          description: "Server displays received information
            Server sends response containing:
            Code = 65(2.01 Created) or 68 (2.04 changed)
            The same Message ID as that of the request sent by the
            client"
           
  /TD_COAP_CORE_05:
    description: Perform GET transaction (NON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a GET request with:
        Type = 1(NON)
        Code = 1(GET)"
      responses:
        200:
          description: "Server sends response containing:
            Type = 1(NON)
            Code= 69(2.05 Content)
            Content format option"
           
  /TD_COAP_CORE_06:
    description: Perform DELETE transaction (NON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a DELETE request with:
        Type = 1(NON)
        Code = 4(DELETE)"
      responses:
        200:
          description: "Server sends response containing:
            Type = 1(NON)
            Code = 66(2.02 Deleted)"

  /TD_COAP_CORE_07:
    description: Perform PUT transaction (NON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a PUT request with:
        Type = 1(NON)
        Code = 3(PUT)
        An arbitrary payload
        Content format option"
      responses:
        200:
          description: "Server sends response containing:
            Type = 1(NON)
            Code = 68 (2.04 Changed) or 65 (2.01 Created)"

  /TD_COAP_CORE_08:
    description: Perform POST transaction (NON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a POST request with:
        Type = 1(NON)
        Code = 2(POST)
        An arbitrary payload
        Content format option"
      responses:
        200:
          description: "Server sends response containing:
            Type = 1(NON)
            Code = 65(2.01 Created) or 68 (2.04 changed)"
           
  /TD_COAP_CORE_09:
    description: Perform GET transaction with separate response (CON mode, no piggyback)
    type: etsi-plugtest
    get:
      description: "The request sent by the client contains:
        Type = 0 (CON)
        Code = 1 (GET)
        Client generated Message ID"
      responses:
        200:
          description: "Server sends response containing:
              Type = 2 (ACK)
              Code = 0
              Same message ID as in the request sent by the client
              empty Payload
            Server sends response containing:
              Type = 0 (CON)
              Code = 69 (2.05 content)
              Server generated Message ID
              Not empty Payload Content format option
            Client sends response containing:
              Type = 2 (ACK)
              Code = 0
              Same message ID as in the response sent by the server in step 4
              empty Payload"
           
  /TD_COAP_CORE_10:
    description: Perform GET transaction containing Token option (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a GET request to server’s resource including Token option
        The request sent by the client contains:
          Type = 0 (CON)
          Code = 1 (GET)
          Option Type = Token
          Token value = a value generated by the client
          Length of the token should be between 1 to 8 B"
      responses:
        200:
          description: "Server sends response containing:
            Code = 69 (2.05 content)
            Length of the token should be between 1 to 8 B
            Token = the same value as in the request sent by the client
            Not empty Payload
            Content format option"

  /TD_COAP_CORE_11:
    description: Perform GET transaction containing token option with a separate response (CON mode)
    type: etsi-plugtest
    get:
      description: "The request sent by the client contains:
        Type = 0 (CON)
        Code = 1 (GET)
        Option Type = Token
        Token value = a value generated by the client.
        Length of the token should be between 1 to 8 B."
      responses:
        200:
          description: "Server sends acknowledgement containing:
              Type = 2 (ACK)
              Code = 0 (Empty)
              same Message-Id as in step 2
              empty Payload
            Server sends response containing:
              Type = 0 (CON)
              Code = 69 (2.05 content)
              Length of the token should be between 1 to 8 B"

  /TD_COAP_CORE_13:
    description: Perform GET transaction containing several URI-Path options (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a confirmable GET request to
        server’s resource
        The request sent by the client contains:
        Type = 0 (CON)
        Code = 1 (GET)
        Option type = URI-Path (one for each path segment), not
        containing ‘/’ symbol"
      responses:
        200:
          description: "Server sends response containing:
            Code = 69 (2.05 content);
            Not empty Payload;
            Content format option;"
     
  /TD_COAP_CORE_14:
    description: Perform GET transaction containing several URI-Query options (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a confirmable GET request with
        three Query parameters (e.g. ?first=1&second=2&third=3) to
        the server’s resource
        The request sent by the client contains:
          Type = 0 (CON);
          Code = 1 (GET)
          Option type = URI-Query (More than one query parameter);"
      responses:
        200:
          description: "Server sends response containing:
            Type = 0 (CON) or 2 (ACK);
            Code = 69 (2.05 content)
            Not empty Payload Content format option;"
     
  /TD_COAP_CORE_17:
    description: Perform GET transaction with a separate response (NON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a non-confirmablserver’s resource
        The request sent by the client contains:
        Type = 1 (NON);
        Code = 1 (GET);
        A message ID generated by the Client;"
      responses:
        200:
          description: "Server DOES NOT send response containing:
            Type = 2 (ACK);
            Same message ID as in the request in step 2;
            empty Payload;
          Server sends response containing:
            Type = 1 (NON);
            Code = 69 (2.05 content);
            Not empty Payload;
            Content format option;"
     
  /TD_COAP_CORE_18:
    description: Perform POST transaction with responses containing 
      several Location-Path options (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a confirmable POST request to
        server’s resource. The request sent by the client contains:
          Type = 0 (CON);
          Code = 2 (POST);
          An arbitrary payload;
          Content-format option;"
      responses:
        200:
          description: "Server sends response containing:
            Code = 65 (2.01 created);
            Option type = Location-Path (one for each segment);
            Option values must contain 
            'location1', 'location2' & 'location3' without containing any ‘/’;"

  /TD_COAP_CORE_19:
    description: Perform POST transaction with responses containing several Location-Query options
      (CON mode)
    type: etsi-plugtest
    get:
      description: "Client is requested to send a confirmable POST request to
        server’s resource  /location-query.
        The request sent by the client contains:
          Type = 0 (CON);
          Code = 2 (POST);
          An arbitrary payload;
          Content-format option;"
      responses:
        200:
          description: "Server sends response containing:
            Code = 65 (2.01 created);
            Two options whose type is Location-Query;
            The first option contains first=1 ;
            The second option contains second=2 ;"
 